FACEBOOK_APP_ID: "1778754202345754"
FACEBOOK_SECRET: "172ab9d9a281308dca7b7794b28b13b5"

TWITTER_API_KEY: "M5u41MZ1RCF9CX1stwIvfe1hD"
TWITTER_SECRET: "XJJncoHwffvQsdEfScObLlBDZ0GX93KlL4uiuXirjZIQkiEXOq"

GOOGLE_CLIENT_ID: "726222497246-6orbq8fq3rqml2b2q3kvrdpea2htm0ii.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "f3i7EDaFfwoObrxFrgWeG5JE"


